In [1]:
import numpy as np
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

Using TensorFlow backend.


In [2]:
X = np.array([
    [0., 0.],
    [0., 1.],
    [1., 0.],
    [1., 1.]
], dtype="float32")

y = np.array([0, 0, 0, 1], dtype="float32")

In [3]:
X

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]], dtype=float32)

In [4]:
y

array([0., 0., 0., 1.], dtype=float32)

In [5]:
model = Sequential()

In [6]:
model.add(Dense(1, input_dim=2, activation="sigmoid"))

In [7]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 1)                 3         
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [8]:
model.compile(loss='binary_crossentropy', optimizer=Adam(lr=0.1), metrics=['acc'])

In [9]:
model.fit(X, y, epochs=100)

Epoch 1/100
4/4 [==============================] - 0s 104ms/step - loss: 0.7034 - acc: 0.7500
Epoch 2/100
4/4 [==============================] - 0s 514us/step - loss: 0.6762 - acc: 0.7500
Epoch 3/100
4/4 [==============================] - 0s 586us/step - loss: 0.6504 - acc: 0.7500
Epoch 4/100
4/4 [==============================] - 0s 499us/step - loss: 0.6258 - acc: 0.7500
Epoch 5/100
4/4 [==============================] - 0s 486us/step - loss: 0.6025 - acc: 0.7500
Epoch 6/100
4/4 [==============================] - 0s 541us/step - loss: 0.5804 - acc: 1.0000
Epoch 7/100
4/4 [==============================] - 0s 476us/step - loss: 0.5594 - acc: 1.0000
Epoch 8/100
4/4 [==============================] - 0s 561us/step - loss: 0.5393 - acc: 1.0000
Epoch 9/100
4/4 [==============================] - 0s 514us/step - loss: 0.5202 - acc: 1.0000
Epoch 10/100
4/4 [==============================] - 0s 635us/step - loss: 0.5020 - acc: 1.0000
Epoch 11/100
4/4 [==============================] - 0s 661u

Epoch 88/100
4/4 [==============================] - 0s 631us/step - loss: 0.1056 - acc: 1.0000
Epoch 89/100
4/4 [==============================] - 0s 1ms/step - loss: 0.1044 - acc: 1.0000
Epoch 90/100
4/4 [==============================] - 0s 486us/step - loss: 0.1031 - acc: 1.0000
Epoch 91/100
4/4 [==============================] - 0s 598us/step - loss: 0.1019 - acc: 1.0000
Epoch 92/100
4/4 [==============================] - 0s 636us/step - loss: 0.1007 - acc: 1.0000
Epoch 93/100
4/4 [==============================] - 0s 681us/step - loss: 0.0996 - acc: 1.0000
Epoch 94/100
4/4 [==============================] - 0s 671us/step - loss: 0.0984 - acc: 1.0000
Epoch 95/100
4/4 [==============================] - 0s 552us/step - loss: 0.0973 - acc: 1.0000
Epoch 96/100
4/4 [==============================] - 0s 524us/step - loss: 0.0962 - acc: 1.0000
Epoch 97/100
4/4 [==============================] - 0s 734us/step - loss: 0.0951 - acc: 1.0000
Epoch 98/100
4/4 [==============================] - 

In [10]:
pred = model.predict(X)
pred

array([[0.00209936],
       [0.1097075 ],
       [0.11308005],
       [0.88190854]], dtype=float32)

In [11]:
predict01 = np.where(pred > 0.5, 1, 0)
print("=" * 30)
print("predict01")
print(predict01)

predict01
[[0]
 [0]
 [0]
 [1]]


In [12]:
predict02 = predict01.flatten()
predict02

array([0, 0, 0, 1])

In [13]:
predict03 = (predict02 == y)
predict03

array([ True,  True,  True,  True])

In [14]:
np.sum(predict03)

4

In [15]:
acc = np.sum(predict03) / 4
acc

1.0

In [16]:
arr=np.array([[0,1]], dtype="float32")
pred = model.predict(arr)
pred

array([[0.1097075]], dtype=float32)

In [17]:
predict01 = np.where(pred > 0.5, 1, 0)
print("=" * 30)
print("predict01")
print(predict01)

predict01
[[0]]


In [18]:
arr=np.array([[1,1]], dtype="float32")
pred = model.predict(arr)
pred

array([[0.88190854]], dtype=float32)

In [19]:
predict01 = np.where(pred > 0.5, 1, 0)
print("=" * 30)
print("predict01")
print(predict01)

predict01
[[1]]
